trigger:
  branches:
    include:
      - master
      - release/**
      - feature/**

variables:
  LOCATION: EastUS
  RESOURCE_GROUP: "OmarLucia-RG"
  RESOURCES_NAMES: "omarlucia"
  STORAGE_ACCOUNT_NAME: "OmarLucia-RG"
  BRANCH_NAME: $[replace(variables['Build.SourceBranch'], 'refs/heads/', '')]

stages:
  - stage: Deploy
    displayName: Deploy ARM Templates and Configure Secrets
    jobs:
      - job: DeployResources
        displayName: Deploy Resources to Azure
        pool:
          vmImage: ubuntu-latest
        steps:
          # 1. Determine the environment based on branch
          - script: |
              # Set environment based on the branch name
              if [[ $(BRANCH_NAME) == "master" ]]; then
                ENVIRONMENT="prd"
              elif [[ $(BRANCH_NAME) == release/* ]]; then
                ENVIRONMENT="test"
              elif [[ $(BRANCH_NAME) == feature/* ]]; then
                ENVIRONMENT="dev"
              else
                echo "Unknown branch: $(BRANCH_NAME)"
                exit 1
              fi
              echo "Deploying to environment: $ENVIRONMENT"
            displayName: Determine Environment
          - script: echo "Deploying to $(ENVIRONMENT) environment"
            displayName: Show Environment

          # 2. Deploy Storage Account ARM Template
          - task: AzureCLI@2
            displayName: Deploy Storage Account ARM Template
            inputs:
              azureSubscription: "Arroyo_Challenge-Test_Omar"
              scriptType: bash
              scriptLocation: inlineScript
              inlineScript: |
                az deployment group create \
                  --resource-group $(RESOURCE_GROUP) \
                  --template-file ARM_Templates/StorageAccount.json \
                  --parameters environment="$ENVIRONMENT" location="$LOCATION" storageAccountName=sa$(RESOURCES_NAMES)

          # 3. Deploy Key Vault ARM Template
          - task: AzureCLI@2
            displayName: Deploy Key Vault ARM Template
            inputs:
              azureSubscription: "Arroyo_Challenge-Test_Omar"
              scriptType: bash
              scriptLocation: inlineScript
              inlineScript: |
                az deployment group create \
                  --resource-group $(RESOURCE_GROUP) \
                  --template-file ARM_Templates/KeyVault.json \
                  --parameters environment="$ENVIRONMENT" location="$LOCATION" keyVaultName="kv$(RESOURCES_NAMES)" sku="Standard_LRS"

          # 4. Get Connection String
          - task: Bash@3
            displayName: Get Connection String
            inputs:
              filePath: Scripts/getSAConnetionString.sh
              arguments: "sa(RESOURCES_NAMES)$(ENVIRONMENT)"

          # 5. Create Secret if not exist
          - task: Bash@3
            displayName: Store Connection String in Key Vault
            inputs:
              filePath: Scripts/createSecret.sh
              arguments: "kv$(RESOURCES_NAMES)-$(ENVIRONMENT) sa-$(RESOURCES_NAMES)-secret-$(ENVIRONMENT) '$(CONNECTION_STRING)'"
